class UserNotFound(Exception): ...


class ChangeRequestNotFound(Exception): ...


class ChangeRequestNotPending(Exception): ...


class GameNotFound(Exception): ...


class GameAccountAlreadyExists(Exception): ...


class GameAlreadyExistsForThisAccount(Exception): ...


class RatingValueError(Exception): ...
