"""Add game url img column

Revision ID: e65d833cf336
Revises: cc39aee8ee17
Create Date: 2024-11-27 21:22:19.913198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65d833cf336'
down_revision: Union[str, None] = 'cc39aee8ee17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_img_url', sa.VARCHAR(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'game_img_url')
    # ### end Alembic commands ###
